import { useEffect,useRef,useState } from 'react';
import api from '../../lib/axios';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '../ui/dialog';
interface Message {role:'user'|'assistant';content:string;timestamp:string;}
export default function ChatWindow({onClose,articleId,articleTitle}: {onClose:()=>void;articleId:string;articleTitle:string}) {
  const [messages,setMessages]=useState<Message[]>([]);const [input,setInput]=useState('');const [pending,setPending]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [retry,setRetry]=useState(0);const lock=useRef(false);const list=useRef<HTMLDivElement>(null);
  useEffect(()=>{const controller=new AbortController();setLoading(true);api.get(`/api/chat/${articleId}`,{signal:controller.signal}).then(({data})=>{setMessages(Array.isArray(data)?data:data.messages||[]);setError('');}).catch(()=>{if(!controller.signal.aborted)setError('聊天记录暂时无法加载，可以稍后重试。');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[articleId,retry]);
  useEffect(()=>{if(list.current)list.current.scrollTop=list.current.scrollHeight;},[messages,pending]);
  const send=async()=>{if(lock.current||!input.trim())return;lock.current=true;setPending(true);setError('');const text=input;try{const {data}=await api.post(`/api/chat/${articleId}`,{content:text.trim()});if(!Array.isArray(data.messages))throw new Error();setMessages(data.messages);setInput('');}catch{setError('暂时无法取得回答，你的问题已保留，请重试。');}finally{lock.current=false;setPending(false);}};
  return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent><DialogTitle>新闻问答</DialogTitle><DialogDescription>{articleTitle}</DialogDescription><div ref={list} className="overflow-y-auto max-h-[45dvh] min-h-32 space-y-4 py-5">{loading&&<p role="status">正在加载对话…</p>}{!loading&&!messages.length&&<p className="text-sm text-muted-foreground">可以围绕这篇新闻提问。</p>}{messages.map((message,index)=><div key={index} className="border-b border-border pb-4"><p className="entry-meta mb-2">{message.role==='user'?'你':'AI 助手'}</p><p className="text-sm whitespace-pre-wrap">{message.content}</p></div>)}{pending&&<p className="text-sm" role="status">正在生成回答…</p>}</div>{error&&<div role="alert"><p className="form-error">{error}</p>{!pending&&<button className="text-link text-sm min-h-11" onClick={()=>setRetry(n=>n+1)}>重新加载对话</button>}</div>}<form onSubmit={event=>{event.preventDefault();void send();}}><div className="form-field"><label htmlFor="article-question">你的问题</label><textarea id="article-question" rows={2} value={input} onChange={event=>setInput(event.target.value)} disabled={pending} placeholder="关于这篇新闻，我想了解…"/></div><button className="ed-button" type="submit" disabled={pending||!input.trim()}>{pending?'正在回答…':'发送问题'}</button></form></DialogContent></Dialog>;
}
