import { Link, useLocation, useNavigate } from 'react-router-dom';
import { FileText, Play, BookOpen, Wrench } from 'lucide-react';
import InteractionButtons from '../InteractionButtons';
import { resourceTypeLabel, type ResourceType } from '../../lib/resourceMeta';
import { formatDate } from '../../lib/contentFormat';
import Illustration from '../Illustration';
interface ResourceCardProps { id: string; title: string; type: ResourceType; downloadCount?: number; views?: number; likes?: number; fileSize?: string; isApproved: boolean; thumbnailUrl?: string; description?: string; tags?: string[]; category?: string; estimatedTime?: string; difficulty?: 'Beginner'|'Intermediate'|'Advanced'; author?: string; isCompact?: boolean; isSquare?: boolean; linkUrl?: string; fileUrl?: string; updatedAt?: string; }
export default function ResourceCard(resource: ResourceCardProps) {
  const location = useLocation(); const navigate = useNavigate(); const Icon = {Document:FileText,Video:Play,Tutorial:BookOpen,Tool:Wrench}[resource.type] || FileText;
  return <article className="resource-entry" data-flip-id={`resource-${resource.id}`}><Illustration kind="resource" size="small" className="entry-illustration"/><Icon size={24} strokeWidth={1.5}/><div data-pet-avoid><div className="entry-meta"><span>{resourceTypeLabel(resource.type)}</span>{resource.category && <span>{resource.category}</span>}{resource.fileSize && <span>{resource.fileSize}</span>}</div><h3 className="mt-1"><Link to={`/resource/${resource.id}`} state={{referrer:location.pathname}}>{resource.title}</Link></h3>{resource.description && <p className="entry-description line-clamp-2">{resource.description}</p>}<div className="entry-meta">{resource.updatedAt && <time>更新于 {formatDate(resource.updatedAt)}</time>}{resource.author && <span>{resource.author}</span>}{resource.downloadCount !== undefined && <span>下载 {resource.downloadCount} 次</span>}</div><div className="mt-2"><Link to={`/resource/${resource.id}`} className="text-link text-sm min-h-11 inline-flex items-center">{resource.linkUrl ? '查看链接' : '查看文件与下载'} →</Link></div><InteractionButtons contentType="Resource" contentId={resource.id} likeCount={resource.likes} shareTitle={resource.title} shareType="resource" onCommentClick={() => navigate(`/comments/resource/${resource.id}`,{state:{referrer:location.pathname}})}/></div></article>;
}
