import PageShell from '../components/PageShell';
import { useRef,useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { useParams,useLocation,useNavigate } from 'react-router-dom';
import api from '../lib/axios';
import { type MongoEvent,formatEventLocation } from '../utils/eventTransform';
import { formatDate,categoryLabel } from '../lib/contentFormat';
import ContentState from '../components/ContentState';
import PageHeading from '../components/PageHeading';
import BackNavigation from '../components/BackNavigation';
import InteractionButtons from '../components/InteractionButtons';
export default function EventDetailPage() {
  const {id}=useParams(); const location=useLocation(); const navigate=useNavigate();const client=useQueryClient();const [pending,setPending]=useState(false);const [message,setMessage]=useState('');const [failed,setFailed]=useState(false);const lock=useRef(false);
  const query=useQuery({queryKey:['event',id],enabled:!!id,queryFn:async()=>(await api.get(`/api/events/${id}`)).data.event as MongoEvent,staleTime:30000});
  const rsvp=useQuery({queryKey:['rsvp',id],enabled:!!id,queryFn:async()=>(await api.get(`/api/events/${id}/rsvp`)).data.rsvp as {status:string}|null,staleTime:10000});
  const event=query.data;const status=rsvp.data?.status;const joined=!!status&&status!=='not_going';const ended=!!event&&new Date(event.endDate||event.startDate).getTime()<Date.now();
  const change=async(cancel:boolean)=>{if(lock.current)return;lock.current=true;setPending(true);setFailed(false);setMessage('');try{const response=cancel?await api.delete(`/api/events/${id}/rsvp`):await api.post(`/api/events/${id}/rsvp`,{status:'going'});if(!response.data.success)throw new Error();client.setQueryData(['rsvp',id],cancel?null:response.data.rsvp);setMessage(cancel?'已取消报名。':response.data.rsvp?.status==='waitlist'?'已加入候补名单，名额释放后会更新报名状态。':'报名成功，已记录你的参与状态。');void client.invalidateQueries({queryKey:['event',id]});void client.invalidateQueries({queryKey:['events']});}catch{setFailed(true);setMessage('报名状态未能更新，请检查网络后重试。');}finally{lock.current=false;setPending(false);}};
  return <PageShell className="reading-page"><BackNavigation referrer={location.state?.referrer} contentType="event" fallbackReferrer="/events"/><ContentState illustration="activity" loading={query.isLoading} error={query.error} empty={!event} emptyTitle="找不到这个活动" onRetry={()=>void query.refetch()}>{event&&<><PageHeading title={event.title} description={event.eventType?categoryLabel(event.eventType):undefined}/><div className="detail-meta"><time>{formatDate(event.startDate)} {new Date(event.startDate).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time><span>{formatEventLocation(event.location)}</span>{event.organizer?.name&&<span>组织者：{event.organizer.name}</span>}<span>已报名 {event.rsvpCount??0} 人{event.maxCapacity?` / 名额 ${event.maxCapacity}`:''}</span></div>{event.imageUrl&&<img className="detail-image" src={event.imageUrl} alt={event.title}/>}<div data-pet-avoid className="reading-body whitespace-pre-wrap">{event.description}</div>{event.prerequisites?.length ? <section className="mt-8"><h2 className="text-xl font-bold mb-3">参加前准备</h2><ul className="list-disc pl-5 space-y-2">{event.prerequisites.map(item=><li key={item}>{item}</li>)}</ul></section>:null}<section className="mt-8 border-y border-border py-6" aria-label="活动报名"><h2 className="text-xl font-bold mb-3">参与活动</h2>{rsvp.isLoading?<p role="status">正在查询报名状态…</p>:rsvp.error?<div role="alert"><p>报名状态暂时无法读取。</p><button className="ed-button secondary mt-3" onClick={()=>void rsvp.refetch()}>重新查询</button></div>:<><p className="text-sm text-muted-foreground mb-4">{status==='waitlist'?'你已在候补名单中。':status==='going'?'你已报名参加。':status==='maybe'?'你目前选择了可能参加。':ended?'活动已结束。':'报名结果和候补情况会在这里显示。'}</p><div className="detail-actions">{joined?<button className="ed-button secondary" disabled={pending} onClick={()=>void change(true)}>{pending?'正在处理…':'取消报名'}</button>:<button className="ed-button" disabled={pending||ended||event.status==='cancelled'} onClick={()=>void change(false)}>{pending?'正在报名…':ended?'活动已结束':'报名参加'}</button>}{event.rsvpLink&&/^https?:\/\//i.test(event.rsvpLink)&&<a className="ed-button secondary" href={event.rsvpLink} target="_blank" rel="noopener noreferrer">外部报名 ↗</a>}</div></>}{message&&<p className={failed?'form-error mt-4':'text-sm mt-4'} role={failed?'alert':'status'}>{message}</p>}</section><InteractionButtons contentType="Event" contentId={id||''} likeCount={event.likeCount||event.likes} shareCount={event.shareCount||event.shares} saveCount={event.saveCount||event.saves} commentCount={event.commentCount||event.discussionCount} shareTitle={event.title} shareType="event" onCommentClick={()=>navigate(`/comments/event/${id}`,{state:{referrer:location.pathname}})}/></>}</ContentState></PageShell>;
}
