import { useRef,useState,useEffect,type FormEvent } from 'react';
import { describeFetchError,describeRequestFailure,safeJson } from '../lib/apiError';
export default function SignUpStepper({onSignIn}: {onSignIn?:()=>void}) {
  const [step,setStep]=useState(1);const [email,setEmail]=useState('');const [uniqueId,setUniqueId]=useState('');const [name,setName]=useState('');const [rosterName,setRosterName]=useState(false);const [password,setPassword]=useState('');const [error,setError]=useState('');const [pending,setPending]=useState(false);const [success,setSuccess]=useState(false);const lock=useRef(false);
  useEffect(()=>{document.getElementById(`signup-${step===1?'email':step===2?'id':rosterName?'password':'name'}`)?.focus();},[step,rosterName]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(lock.current)return;setError('');if(step===1&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setError('请输入有效的邮箱地址。');return;}if(step===2&&!uniqueId.trim()){setError('请输入班级名单中的学号。');return;}if(step===3&&(!name.trim()||password.length<8)){setError(!name.trim()?'请输入真实姓名。':'密码至少需要 8 位。');return;}lock.current=true;setPending(true);try{const body=step===1?{email:email.trim()}:step===2?{email:email.trim(),uniqueId:uniqueId.trim()}:{email:email.trim(),uniqueId:uniqueId.trim(),password,name:name.trim()};const response=await fetch(`/api/auth/signup-step${step}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await safeJson<{error?:string;name?:string}>(response);if(!response.ok||!data)throw new Error(data?.error||describeRequestFailure(response,'注册校验失败'));if(step===2){setName(data.name||'');setRosterName(!!data.name);}if(step===3)setSuccess(true);else setStep(s=>s+1);}catch(error){setError(describeFetchError(error,'暂时无法完成注册，请稍后重试。'));}finally{lock.current=false;setPending(false);}};
  if(success)return <div role="status"><h3 className="text-xl font-bold mb-3">注册成功</h3><p className="mb-5">现在可以使用 {email} 登录。</p><button className="ed-button" onClick={onSignIn}>前往登录</button></div>;
  return <form onSubmit={submit} noValidate aria-busy={pending}><ol className="flex gap-4 text-xs text-muted-foreground mb-6" aria-label="注册进度">{['验证邮箱','验证学号','设置密码'].map((label,index)=><li key={label} aria-current={step===index+1?'step':undefined} className={step===index+1?'text-primary font-bold':''}>{index+1}. {label}</li>)}</ol>{step===1&&<div className="form-field"><label htmlFor="signup-email">邮箱</label><input id="signup-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} aria-describedby="signup-note"/><p id="signup-note" className="text-xs text-muted-foreground">填写班级名单中登记的邮箱。</p></div>}{step===2&&<div className="form-field"><label htmlFor="signup-id">学号</label><input id="signup-id" autoComplete="off" value={uniqueId} onChange={e=>setUniqueId(e.target.value)}/></div>}{step===3&&<>{!rosterName&&<div className="form-field"><label htmlFor="signup-name">真实姓名</label><input id="signup-name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></div>}{rosterName&&<p className="mb-5 text-sm">已验证：{name}</p>}<div className="form-field"><label htmlFor="signup-password">设置密码</label><input id="signup-password" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} aria-describedby="password-help"/><p id="password-help" className="text-xs text-muted-foreground">至少 8 位，建议同时包含字母、数字和符号。</p></div></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="flex gap-3">{step>1&&<button type="button" className="ed-button secondary" disabled={pending} onClick={()=>{setError('');setStep(s=>s-1);}}>上一步</button>}<button type="submit" className="ed-button flex-1" disabled={pending}>{pending?'正在验证…':step===3?'完成注册':'下一步'}</button></div></form>;
}
