import { useRef,useState,type FormEvent } from 'react';
import { useNavigate,useLocation } from 'react-router-dom';
import { Eye,EyeOff } from 'lucide-react';
import { Button } from '../components/ui/button';
import { useUser } from '../context/userContextState';
import { describeFetchError,describeRequestFailure,safeJson } from '../lib/apiError';
interface LoginResponse {token?:string;user?:{email:string;name:string;uniqueId:string};error?:string;}
export default function SignInForm() {
  const [uniqueId,setUniqueId]=useState('');const [password,setPassword]=useState('');const [visible,setVisible]=useState(false);const [error,setError]=useState('');const [pending,setPending]=useState(false);const lock=useRef(false);const {login}=useUser();const navigate=useNavigate();const location=useLocation();
  const submit=async(event:FormEvent)=>{event.preventDefault();if(lock.current)return;setError('');if(!/^[A-Za-z0-9_-]{1,64}$/.test(uniqueId.trim())){setError('请输入有效的学号或管理员编号。');document.getElementById('login-student-id')?.focus();return;}if(!password){setError('请输入密码。');document.getElementById('login-password')?.focus();return;}lock.current=true;setPending(true);try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uniqueId:uniqueId.trim(),password})});const data=await safeJson<LoginResponse>(response);if(!response.ok||!data)throw new Error(data?.error||describeRequestFailure(response,'登录失败'));if(!data.token||!data.user)throw new Error('登录响应不完整，请稍后重试。');login(data.token,data.user);const from=location.state?.from;navigate(typeof from==='string'&&from.startsWith('/')&&!from.startsWith('//')?from:'/',{replace:true});}catch(error){setError(describeFetchError(error,'登录未成功，请检查学号和密码。'));}finally{lock.current=false;setPending(false);}};
  return <form onSubmit={submit} noValidate aria-busy={pending}><div className="form-field"><label htmlFor="login-student-id">学号</label><input id="login-student-id" type="text" autoComplete="username" value={uniqueId} onChange={e=>setUniqueId(e.target.value)} required aria-invalid={!!error} aria-describedby={error?'login-error':undefined}/></div><div className="form-field"><label htmlFor="login-password">密码</label><div className="relative"><input id="login-password" className="pr-12" type={visible?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required aria-invalid={!!error} aria-describedby={error?'login-error':undefined}/><button className="icon-control absolute right-0 top-0" type="button" aria-label={visible?'隐藏密码':'显示密码'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff/>:<Eye/>}</button></div></div>{error&&<p id="login-error" className="form-error" role="alert">{error}</p>}<Button className="ed-button w-full" loading={pending} loadingLabel="正在登录…" type="submit">登录班级网站</Button></form>;
}
