import { useRef,useState } from 'react';
import { MoreHorizontal } from 'lucide-react';
import type { Comment } from '../hooks/useComments';
import { timeAgo } from '../lib/announcementMeta';
import ConfirmationDialog from './ui/ConfirmationDialog';
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem } from './ui/dropdown-menu';
interface CommentListProps {comments:Comment[];loading?:boolean;onEdit?:(id:string,content:string)=>Promise<void>;onDelete?:(id:string)=>Promise<void>;onLoadMore?:()=>void;hasMore?:boolean;currentUser?:{id?:string;_id?:string;name?:string;email?:string};}
function CommentItem({comment,onEdit,onDelete,currentUser}: {comment:Comment}&Pick<CommentListProps,'onEdit'|'onDelete'|'currentUser'>) {
  const [edit,setEdit]=useState(false);const [value,setValue]=useState(comment.text);const [confirm,setConfirm]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState('');const lock=useRef(false);
  const mine=!!comment.userId?._id&&String(currentUser?.id||currentUser?._id)===String(comment.userId._id);const deleted=comment.status==='deleted';
  const change=async(remove:boolean)=>{if(lock.current)return;if(!remove&&!value.trim()){setError('评论内容不能为空。');return;}lock.current=true;setPending(true);setError('');try{if(remove)await onDelete?.(comment._id);else await onEdit?.(comment._id,value.trim());setEdit(false);setConfirm(false);}catch{setConfirm(false);setError(remove?'评论删除未成功，请重试。':'修改未成功，内容已保留，请重试。');}finally{lock.current=false;setPending(false);}};
  return <article className="py-5 border-b border-border"><div className="flex items-start gap-3"><div className="flex-1"><h3 className="font-semibold text-sm">{comment.userId?.name||'班级成员'}</h3><span className="entry-meta">{timeAgo(comment.createdAt)}{comment.isEdited&&' · 已编辑'}</span></div>{mine&&!deleted&&<DropdownMenu><DropdownMenuTrigger asChild><button className="icon-control" aria-label="管理这条评论"><MoreHorizontal/></button></DropdownMenuTrigger><DropdownMenuContent align="end">{onEdit&&<DropdownMenuItem onSelect={()=>{setValue(comment.text);setEdit(true);}}>编辑评论</DropdownMenuItem>}{onDelete&&<DropdownMenuItem onSelect={()=>setConfirm(true)} className="text-destructive">删除评论</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>}</div>{edit?<form className="mt-3" onSubmit={event=>{event.preventDefault();void change(false);}}><div className="form-field"><label htmlFor={`edit-${comment._id}`}>修改评论</label><textarea autoFocus id={`edit-${comment._id}`} rows={3} maxLength={2000} value={value} onChange={event=>setValue(event.target.value)} disabled={pending}/></div><div className="flex gap-3"><button className="ed-button" disabled={pending} type="submit">{pending?'正在保存…':'保存修改'}</button><button className="ed-button secondary" disabled={pending} type="button" onClick={()=>setEdit(false)}>取消</button></div></form>:<p className="mt-3 whitespace-pre-wrap break-words">{deleted?'这条评论已删除。':comment.text}</p>}{error&&<p className="form-error mt-3" role="alert">{error}</p>}<ConfirmationDialog isOpen={confirm} onClose={()=>{if(!pending)setConfirm(false);}} title="删除评论" message="确认删除这条评论？删除后无法恢复。" confirmText="删除" isLoading={pending} onConfirm={()=>void change(true)}/></article>;
}
export default function CommentList({comments,loading,onLoadMore,hasMore,...props}:CommentListProps) {
  return <>{comments.map(comment=><CommentItem key={comment._id} comment={comment} {...props}/>)}{!comments.length&&!loading&&<p className="py-6 text-muted-foreground">暂无评论，来分享你的想法。</p>}{loading&&<p className="py-4 text-muted-foreground" role="status">正在加载评论…</p>}{hasMore&&<button className="ed-button secondary mt-5" onClick={onLoadMore} disabled={loading}>加载更多评论</button>}</>;
}
