import { useId,useRef,useState } from 'react';
import { Smile } from 'lucide-react';
import api from '../lib/axios';
import EmojiPicker from './EmojiPicker';
import { useQueryClient } from '@tanstack/react-query';
import { invalidateCommentCounters } from '../lib/commentCounters';
interface CommentInputProps {onSubmit?:(content:string)=>Promise<void>;placeholder?:string;loading?:boolean;disabled?:boolean;className?:string;contentType?:string;contentId?:string;onCommentAdded?:()=>void;}
export default function CommentInput({onSubmit,placeholder='说说你的想法…',loading=false,disabled=false,className='',contentType,contentId,onCommentAdded}:CommentInputProps) {
  const client=useQueryClient();
  const id=useId();const [value,setValue]=useState('');const [pending,setPending]=useState(false);const [status,setStatus]=useState('');const [error,setError]=useState('');const [emoji,setEmoji]=useState(false);const lock=useRef(false);const input=useRef<HTMLTextAreaElement>(null);const trigger=useRef<HTMLButtonElement>(null);
  const send=async()=>{if(lock.current||disabled||loading)return;setError('');setStatus('');if(!value.trim()){setError('请填写评论内容。');input.current?.focus();return;}lock.current=true;setPending(true);try{if(onSubmit)await onSubmit(value.trim());else if(contentType&&contentId){await api.post(`/api/comments/${contentType}/${contentId}`,{content:value.trim()});invalidateCommentCounters(client,contentType,contentId);onCommentAdded?.();}else throw new Error();setValue('');setStatus('评论已发布。');}catch{setError('评论发布未成功，内容已保留，请重试。');}finally{lock.current=false;setPending(false);}};
  return <form className={`relative ${className}`} onSubmit={event=>{event.preventDefault();void send();}} aria-busy={pending}><div className="form-field"><label htmlFor={id}>你的评论</label><textarea id={id} ref={input} value={value} onChange={event=>setValue(event.target.value)} placeholder={placeholder} maxLength={2000} rows={3} disabled={disabled||pending} aria-invalid={!!error} aria-describedby={error?`${id}-error`:`${id}-hint`} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'&&!event.nativeEvent.isComposing){event.preventDefault();void send();}}}/></div><div className="flex justify-between items-center gap-3"><button ref={trigger} className="icon-control" type="button" aria-label="插入表情" aria-expanded={emoji} onClick={()=>setEmoji(v=>!v)}><Smile/></button><span id={`${id}-hint`} className="entry-meta">{value.length} / 2000</span><button className="ed-button" type="submit" disabled={pending||disabled||loading}>{pending?'正在发布…':'发布评论'}</button></div><EmojiPicker isOpen={emoji} onClose={()=>setEmoji(false)} triggerRef={trigger} onEmojiSelect={symbol=>{const el=input.current;const start=el?.selectionStart??value.length;const end=el?.selectionEnd??start;setValue(old=>(old.slice(0,start)+symbol+old.slice(end)).slice(0,2000));setEmoji(false);requestAnimationFrame(()=>{el?.focus();el?.setSelectionRange(start+symbol.length,start+symbol.length);});}}/>{error&&<p id={`${id}-error`} className="form-error mt-3" role="alert">{error}</p>}{status&&<p className="text-sm mt-3" role="status">{status}</p>}</form>;
}
