import { useEffect,useRef,useState } from 'react';
import { ChevronLeft,ChevronRight,ZoomIn,ZoomOut } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from './ui/dialog';
interface GalleryImage { index?:number;url?:string;contentType?:string;originalName?:string;caption?:string; }
export default function EventGallery({eventId,gallery,title="活动相册"}: {eventId:string;gallery:GalleryImage[];title?:string}) {
  const [selected,setSelected]=useState<number|null>(null);const [zoom,setZoom]=useState(1);const [errors,setErrors]=useState<Set<number>>(new Set());const touch=useRef<number|null>(null);
  const src=(index:number)=>gallery[index]?.url||`/api/past-events/${eventId}/gallery/${gallery[index]?.index??index}`;
  const move=(amount:number)=>{setSelected(index=>index===null?null:Math.min(gallery.length-1,Math.max(0,index+amount)));setZoom(1);};
  useEffect(()=>{if(selected===null)return;const key=(event:KeyboardEvent)=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();setSelected(index=>index===null?null:Math.min(gallery.length-1,Math.max(0,index+(event.key==='ArrowLeft'?-1:1))));setZoom(1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected,gallery.length]);
  if(!gallery.length)return null;
  return <section className="mt-8" aria-label={title}><div className="section-heading"><h2>{title}</h2><span className="entry-meta">{gallery.length} 张照片</span></div><div className="gallery-grid">{gallery.map((photo,index)=><button key={index} aria-label={`查看第 ${index+1} 张照片${photo.caption?'：'+photo.caption:''}`} onClick={()=>{setSelected(index);setZoom(1);}} disabled={errors.has(index)}>{errors.has(index)?<span className="block aspect-[4/3] bg-secondary p-4 text-sm">图片暂时无法加载</span>:<img src={src(index)} alt={photo.caption||`活动照片 ${index+1}`} loading="lazy" onError={()=>setErrors(previous=>new Set(previous).add(index))}/>}</button>)}</div><Dialog open={selected!==null} onOpenChange={open=>{if(!open){setSelected(null);setZoom(1);}}}><DialogContent className="lightbox-panel"><DialogTitle className="pr-12">{selected!==null?gallery[selected]?.caption||`活动照片 ${selected+1}`:'活动照片'}</DialogTitle><DialogDescription className="sr-only">方向键或左右滑动切换照片，Esc 关闭，支持缩放。</DialogDescription>{selected!==null&&<><div className="lightbox-image" onTouchStart={event=>{touch.current=event.touches[0]?.clientX??null;}} onTouchEnd={event=>{const end=event.changedTouches[0]?.clientX;if(zoom===1&&touch.current!==null&&end!==undefined&&Math.abs(end-touch.current)>60)move(end>touch.current?-1:1);touch.current=null;}}><img src={src(selected)} alt={gallery[selected]?.caption||`活动照片 ${selected+1}`} style={{transform:`scale(${zoom})`,transformOrigin:'center'}}/></div><div className="lightbox-controls"><button className="icon-control" aria-label="上一张照片" disabled={selected===0} onClick={()=>move(-1)}><ChevronLeft/></button><span className="text-sm">{selected+1} / {gallery.length}</span><button className="icon-control" aria-label="下一张照片" disabled={selected===gallery.length-1} onClick={()=>move(1)}><ChevronRight/></button><button className="icon-control" aria-label="缩小照片" disabled={zoom===1} onClick={()=>setZoom(z=>Math.max(1,z-.5))}><ZoomOut/></button><button className="icon-control" aria-label="放大照片" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.5))}><ZoomIn/></button><button className="filter-option" onClick={()=>setZoom(1)}>还原</button></div></>}</DialogContent></Dialog></section>;
}
