import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Command } from 'cmdk';
import { Search } from 'lucide-react';
import api from '../lib/axios';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
interface Result { id: string; type: string; title: string; description?: string; url: string; }
const labels: Record<string,string> = { news:'新闻', News:'新闻', event:'活动', Event:'活动', resource:'资源', Resource:'资源', social:'班级动态', SocialPost:'班级动态', announcement:'公告', pastEvent:'往期活动' };
export default function SearchDialog({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const navigate = useNavigate();
  const [query, setQuery] = useState(''); const [results, setResults] = useState<Result[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState(false); const [retry, setRetry] = useState(0);
  useEffect(() => { if (!isOpen) { setQuery(''); setResults([]); return; } if (!query.trim()) { setResults([]); setPending(false); setError(false); return; } const controller = new AbortController(); setPending(true); setError(false); const timer = window.setTimeout(async () => { try { const { data } = await api.get('/api/search', { params:{q:query.trim(),limit:20}, signal:controller.signal }); if (!controller.signal.aborted) setResults(data.results || []); } catch { if (!controller.signal.aborted) { setError(true); setResults([]); } } finally { if (!controller.signal.aborted) setPending(false); } },300); return () => { clearTimeout(timer); controller.abort(); }; }, [query,isOpen,retry]);
  const groups = [...new Set(results.map(result => result.type))];
  return <Dialog open={isOpen} onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="search-panel"><DialogTitle>搜索班级内容</DialogTitle><DialogDescription>查找新闻、活动、资源和班级动态。</DialogDescription><Command shouldFilter={false} label="搜索结果"><div className="form-field mt-4"><label className="sr-only" htmlFor="site-search">搜索关键词</label><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><Command.Input id="site-search" value={query} onValueChange={setQuery} placeholder="输入关键词…" className="w-full min-h-11 border border-input bg-background pl-10 pr-3 py-2"/></div></div><Command.List className="max-h-[50vh] overflow-y-auto" aria-busy={pending}>{pending ? <p className="py-4 text-muted-foreground" role="status">正在搜索…</p> : error ? <div role="alert"><p>搜索暂时不可用，请稍后重试。</p><button className="ed-button secondary mt-3" onClick={() => setRetry(n => n+1)}>重新搜索</button></div> : query.trim() && !results.length ? <Command.Empty className="py-6 text-muted-foreground">没有找到相关内容，试试其他关键词。</Command.Empty> : !query.trim() ? <p className="py-6 text-muted-foreground">输入标题或内容关键词开始搜索。</p> : groups.map(type => <Command.Group key={type} heading={labels[type] || '其他内容'} className="mb-3 text-sm text-muted-foreground">{results.filter(r => r.type === type).map((result,index) => <Command.Item key={`${result.type}-${result.id}-${index}`} value={`${result.type}:${result.id}:${index}`} className="search-result" onSelect={() => { onClose(); navigate(result.url); }}><div><h3>{result.title}</h3>{result.description && <p className="line-clamp-2">{result.description}</p>}</div></Command.Item>)}</Command.Group>)}</Command.List></Command><p className="search-hint">↑ ↓ 选择 · Enter 打开 · Esc 关闭</p></DialogContent></Dialog>;
}
