import { useEffect, useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { activityApi, activityError } from '../../lib/activityApi';
import { REGISTRATION_LABELS } from '../../lib/activityMeta';
import type { ActivityMember, MemberFilter, ReviewResult } from '../../types/activity';
import { AdminButton, Badge, DataTable, EmptyState, ErrorState, LoadingState, Modal, Pagination, Panel, SelectInput, Td, TextArea, TextInput, Th, Tr } from './components';
import { formatDate } from './formatting';
import UserAvatarImage from '../../components/UserAvatarImage';

const filters: Array<{ value: MemberFilter; label: string }> = [{ value: 'all', label: '全部成员' }, { value: 'registered', label: '已报名' }, { value: 'pending', label: '待审核' }, { value: 'approved', label: '已通过' }, { value: 'rejected', label: '未通过' }, { value: 'cancelled', label: '已取消' }, { value: 'unregistered', label: '未报名' }];
export default function ActivityRegistrations({ id, active, onChanged }: { id: string; active: boolean; onChanged: () => void }) {
  const client = useQueryClient(); const [filter, setFilter] = useState<MemberFilter>('all'); const [search, setSearch] = useState(''); const [keyword, setKeyword] = useState(''); const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<string[]>([]); const [reviewing, setReviewing] = useState<{ members: ActivityMember[]; status: 'APPROVED' | 'REJECTED' } | null>(null); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [results, setResults] = useState<ReviewResult[] | null>(null); const lock = useRef(false);
  const query = useQuery({ queryKey: ['activity-registrations', id, filter, keyword, page], enabled: active, queryFn: ({ signal }) => activityApi.members(id, { filter, search: keyword || undefined, page, limit: 20 }, signal), staleTime: 10000 });
  useEffect(() => { setSelected([]); }, [filter, keyword, page]);
  const candidates = query.data?.members.filter(member => member.status === 'PENDING' && member.userId && member.registration) || [];
  const openReview = (members: ActivityMember[], status: 'APPROVED' | 'REJECTED') => { setReviewing({ members, status }); setNote(''); setError(''); setResults(null); };
  const review = async () => {
    if (!reviewing || lock.current) return;
    lock.current = true; setBusy(true); setError('');
    try {
      const registrations = reviewing.members.map(member => ({ userId: member.userId!, version: member.registration!.version }));
      if (registrations.length === 1) { await activityApi.review(id, registrations[0].userId, reviewing.status, registrations[0].version, note.trim()); setResults([{ userId: registrations[0].userId, success: true }]); }
      else { const response = await activityApi.bulkReview(id, registrations, reviewing.status, note.trim()); setResults(response.results); }
      setReviewing(null); setSelected([]); void client.invalidateQueries({ queryKey: ['activity-registrations', id] }); onChanged();
    } catch (cause) { setError(activityError(cause)); void query.refetch(); }
    finally { lock.current = false; setBusy(false); }
  };
  return <Panel title="报名管理" description="未报名表示从未提交申请；已取消和未通过的记录分别保留。">
    {query.data && <div className="mb-5 flex flex-wrap gap-x-5 gap-y-2 text-sm"><span>全班 {query.data.stats.totalMembers}</span><span>已报名 {query.data.stats.registered}</span><span>待审核 {query.data.stats.pending}</span><span>已通过 {query.data.stats.approved}</span><span>未通过 {query.data.stats.rejected}</span><span>已取消 {query.data.stats.cancelled}</span><span>未报名 {query.data.stats.unregistered}</span></div>}
    <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><SelectInput aria-label="报名状态筛选" className="sm:w-36" value={filter} onChange={e => { setFilter(e.target.value as MemberFilter); setPage(1); }} options={filters}/><form className="flex min-w-0 flex-1 gap-2 sm:min-w-[14rem]" onSubmit={e => { e.preventDefault(); setKeyword(search.trim()); setPage(1); }}><TextInput className="min-w-0 flex-1" aria-label="搜索成员姓名" placeholder="搜索姓名" value={search} onChange={e => setSearch(e.target.value)}/><AdminButton type="submit" variant="secondary" className="shrink-0 whitespace-nowrap">搜索</AdminButton></form><AdminButton variant="secondary" className="shrink-0 whitespace-nowrap" onClick={() => void query.refetch()}>刷新名单</AdminButton></div>
    {selected.length > 0 && <div className="mb-4 flex flex-wrap items-center gap-3"><span className="text-sm">已选择 {selected.length} 位待审核成员</span><AdminButton disabled={busy} onClick={() => openReview(candidates.filter(member => selected.includes(member.userId!)), 'APPROVED')}>批量批准</AdminButton><AdminButton variant="secondary" disabled={busy} onClick={() => openReview(candidates.filter(member => selected.includes(member.userId!)), 'REJECTED')}>批量拒绝</AdminButton></div>}
    {results && <div className="mb-4 border border-border p-3 text-sm" role="status"><p>审核完成：成功 {results.filter(result => result.success).length} 人，失败 {results.filter(result => !result.success).length} 人。</p>{results.filter(result => !result.success).map(result => <p key={result.userId} className="mt-1 text-destructive">{query.data?.members.find(member => member.userId === result.userId)?.name || '成员'}：{result.error || '未完成，请刷新名单后重试。'}</p>)}</div>}
    {error && !reviewing && <p className="mb-3 text-sm text-destructive" role="alert">{error}</p>}
    {query.isLoading ? <LoadingState label="正在读取报名名单…"/> : query.error ? <ErrorState message={activityError(query.error)} onRetry={() => void query.refetch()}/> : !query.data?.members.length ? <EmptyState title={filter === 'unregistered' ? '所有成员都已有申请记录' : '当前筛选没有成员'} description="调整状态或姓名搜索查看其他成员。"/> : <><DataTable head={<><Th><input type="checkbox" aria-label="选择本页待审核成员" disabled={!candidates.length} checked={!!candidates.length && candidates.every(member => selected.includes(member.userId!))} onChange={e => setSelected(e.target.checked ? candidates.map(member => member.userId!) : [])}/></Th><Th>成员</Th><Th>报名状态</Th><Th>申请 / 审核时间</Th><Th>操作</Th></>}>{query.data.members.map(member => <Tr key={member.id}><Td>{member.status === 'PENDING' && member.userId && member.registration && <input type="checkbox" aria-label={`选择${member.name}`} checked={selected.includes(member.userId)} onChange={e => setSelected(previous => e.target.checked ? [...previous, member.userId!] : previous.filter(userId => userId !== member.userId))}/>}</Td><Td><div className="flex items-center gap-3"><UserAvatarImage src={member.avatar} identity={member.userId || member.id} alt="" className="h-9 w-9 rounded-full object-cover"/><div><p className="font-medium">{member.name}</p>{member.uniqueId && <p className="text-xs text-muted-foreground">{member.uniqueId}</p>}</div></div></Td><Td><Badge tone={member.status === 'APPROVED' ? 'success' : member.status === 'REJECTED' ? 'danger' : 'neutral'}>{REGISTRATION_LABELS[member.status]}</Badge>{member.registration?.legacyStatus && <p className="mt-1 text-xs text-muted-foreground">保留历史申请</p>}</Td><Td className="text-xs"><p>{formatDate(member.registration?.createdAt, true)}</p>{member.registration?.reviewedAt && <p className="mt-1 text-muted-foreground">审核于 {formatDate(member.registration.reviewedAt, true)}</p>}{member.registration?.reviewNote && <p className="mt-1 max-w-xs whitespace-pre-wrap text-muted-foreground">{member.registration.reviewNote}</p>}</Td><Td>{member.status === 'PENDING' && member.userId && member.registration ? <div className="flex gap-2"><AdminButton disabled={busy} onClick={() => openReview([member], 'APPROVED')}>批准</AdminButton><AdminButton variant="secondary" disabled={busy} onClick={() => openReview([member], 'REJECTED')}>拒绝</AdminButton></div> : <span className="text-xs text-muted-foreground">—</span>}</Td></Tr>)}</DataTable><Pagination page={query.data.pagination.page} pages={Math.max(1, query.data.pagination.pages)} total={query.data.pagination.total} onChange={setPage}/></>}
    <Modal open={!!reviewing} title={`${reviewing?.status === 'APPROVED' ? '批准' : '拒绝'} ${reviewing?.members.length || 0} 人的报名`} onClose={() => { if (!busy) setReviewing(null); }} width="max-w-md" footer={<><AdminButton variant="secondary" disabled={busy} onClick={() => setReviewing(null)}>取消</AdminButton><AdminButton loading={busy} onClick={() => void review()}>确认{reviewing?.status === 'APPROVED' ? '批准' : '拒绝'}</AdminButton></>}><p className="mb-3 text-sm">{reviewing?.members.map(member => member.name).join('、')}</p><label className="block text-sm">审核说明（可选）<TextArea className="mt-2" maxLength={500} value={note} onChange={e => setNote(e.target.value)}/></label>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</Modal>
  </Panel>;
}
