import { useEffect, useRef, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { activityApi, activityError } from '../../lib/activityApi';
import { ACTIVITY_STATUS_LABELS, PHASE_LABELS, activityTypeLabel } from '../../lib/activityMeta';
import { AdminButton, Badge, ErrorState, LoadingState, PageHeader, Panel, TextArea } from './components';
import { updateEvent } from './adminApi';
import { formatDate } from './formatting';
import ActivityEditor from './ActivityEditor';
import ActivityRegistrations from './ActivityRegistrations';
import ActivityMediaManager from './ActivityMediaManager';

const tabs = [{ value: 'overview', label: '概览' }, { value: 'registrations', label: '报名管理' }, { value: 'media', label: '活动相册' }, { value: 'summary', label: '活动总结' }];
export default function AdminEventDetail() {
  const { id = '' } = useParams(); const [params, setParams] = useSearchParams(); const tab = tabs.some(item => item.value === params.get('tab')) ? params.get('tab')! : 'overview';
  const client = useQueryClient(); const [editing, setEditing] = useState(false); const [summary, setSummary] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const lock = useRef(false); const summaryDirty = useRef(false);
  const query = useQuery({ queryKey: ['activity-admin', id], queryFn: ({ signal }) => activityApi.detail(id, true, signal), staleTime: 15000, refetchInterval: 240000, refetchOnWindowFocus: true }); const event = query.data?.event; const stats = query.data?.stats;
  useEffect(() => { summaryDirty.current = false; setSummary(''); setError(''); setNotice(''); setEditing(false); }, [id]);
  useEffect(() => { if (!summaryDirty.current) setSummary(event?.summary || ''); }, [event?.summary]);
  const refresh = () => { void client.invalidateQueries({ queryKey: ['activity-admin', id] }); void client.invalidateQueries({ queryKey: ['event', id] }); void client.invalidateQueries({ queryKey: ['events'] }); void client.invalidateQueries({ queryKey: ['activity-media', id] }); };
  const action = async (work: () => Promise<unknown>, success: string) => { if (lock.current) return; lock.current = true; setBusy(true); setError(''); setNotice(''); try { await work(); setNotice(success); refresh(); } catch (cause) { setError(activityError(cause)); } finally { lock.current = false; setBusy(false); } };
  return <>
    <Link className="mb-4 inline-flex min-h-11 items-center text-sm text-primary" to="/admin/events">返回活动管理</Link>
    {query.isLoading ? <LoadingState label="正在读取活动…"/> : query.error ? <ErrorState message={activityError(query.error)} onRetry={() => void query.refetch()}/> : event && <>
      <PageHeader title={event.title} subtitle={activityTypeLabel(event.eventType)} actions={<><AdminButton variant="secondary" onClick={() => setEditing(true)}>编辑基本信息</AdminButton>{event.status === 'draft' && <AdminButton loading={busy} onClick={() => void action(() => updateEvent(id, { status: 'published' }), '活动已发布。')}>发布活动</AdminButton>}{event.phase === 'ENDED' && ['published', 'completed'].includes(event.status || '') && !event.deletedAt && <AdminButton variant="secondary" loading={busy} onClick={() => void action(() => activityApi.archive(id), '活动已归档，报名与照片继续保留。')}>归档</AdminButton>}{event.deletedAt && <AdminButton loading={busy} onClick={() => void action(() => activityApi.restore(id), '活动已恢复。')}>恢复展示</AdminButton>}<Link className="inline-flex min-h-11 items-center px-3 text-sm text-primary" to={`/events/${id}`}>成员端预览</Link></>}/>
      <div className="mb-5 flex flex-wrap items-center gap-3"><Badge tone={event.status === 'published' ? 'success' : 'neutral'}>{ACTIVITY_STATUS_LABELS[event.status || ''] || event.status}</Badge>{event.phase && <Badge>{PHASE_LABELS[event.phase]}</Badge>}{event.deletedAt && <Badge tone="warning">成员端已隐藏</Badge>}</div>
      {error && <p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="mb-4 text-sm">{notice}</p>}
      <div className="mb-6 flex flex-wrap gap-2 border-b border-border pb-3" role="tablist" aria-label="活动详情">{tabs.map(item => <button key={item.value} id={`activity-tab-${item.value}`} role="tab" aria-controls={`activity-panel-${item.value}`} aria-selected={tab === item.value} className={`min-h-11 px-4 text-sm ${tab === item.value ? 'border-b-2 border-primary font-medium text-primary' : 'text-muted-foreground'}`} onClick={() => setParams({ tab: item.value })}>{item.label}</button>)}</div>
      <section role="tabpanel" id="activity-panel-overview" aria-labelledby="activity-tab-overview" hidden={tab !== 'overview'}><Panel title="活动信息"><dl className="grid gap-x-8 gap-y-4 text-sm sm:grid-cols-2">{[['活动类型', activityTypeLabel(event.eventType)], ['举办形式', ({ physical: '线下', virtual: '线上', hybrid: '线上线下结合' } as Record<string, string>)[event.location?.type || ''] || '—'], ['开始时间', formatDate(event.startDate, true)], ['结束时间', formatDate(event.endDate, true)], ['报名截止时间', event.rsvpDeadline ? formatDate(event.rsvpDeadline, true) : '活动结束时截止'], ['地址', event.location?.address || '—'], ['教室 / 房间', event.location?.room || '—'], ['线上链接', event.location?.virtualLink || '—'], ['人数上限', event.maxCapacity ? `${event.maxCapacity} 人（审核通过）` : '不限'], ['创建时间', formatDate(event.createdAt, true)], ['更新时间', formatDate(event.updatedAt, true)]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl>{(event.coverUrl || event.imageUrl) && <img src={event.coverUrl || event.imageUrl} alt="活动封面" className="mt-6 max-h-96 w-full object-contain"/>}<h2 className="mb-3 mt-6 font-medium">活动介绍</h2><div className="whitespace-pre-wrap break-words text-sm leading-8">{event.description}</div>{stats && <div className="mt-6 flex flex-wrap gap-5 border-t border-border pt-5 text-sm"><span>已报名 {stats.registered}</span><span>待审核 {stats.pending}</span><span>已通过 {stats.approved}</span><span>未通过 {stats.rejected}</span><span>未报名 {stats.unregistered}</span><button className="text-primary" onClick={() => setParams({ tab: 'registrations' })}>查看名单</button></div>}</Panel></section>
      <section role="tabpanel" id="activity-panel-registrations" aria-labelledby="activity-tab-registrations" hidden={tab !== 'registrations'}><ActivityRegistrations key={id} id={id} active={tab === 'registrations'} onChanged={refresh}/></section>
      <section role="tabpanel" id="activity-panel-media" aria-labelledby="activity-tab-media" hidden={tab !== 'media'}><ActivityMediaManager key={id} id={id} coverUrl={event.coverUrl || event.imageUrl} coverMediaId={event.coverMediaId} active={tab === 'media'} onChanged={refresh}/></section>
      <section role="tabpanel" id="activity-panel-summary" aria-labelledby="activity-tab-summary" hidden={tab !== 'summary'}><Panel title="活动总结" description="记录开展情况、主要内容与活动收获，原始活动介绍继续保留。"><label className="block text-sm">总结正文<TextArea value={summary} maxLength={10000} onChange={e => { summaryDirty.current = true; setSummary(e.target.value); }} className="mb-4 mt-3 min-h-64"/></label><AdminButton loading={busy} onClick={() => void action(async () => { await activityApi.summary(id, summary.trim()); summaryDirty.current = false; }, '活动总结已保存。')}>保存总结</AdminButton></Panel></section>
      <ActivityEditor key={id} open={editing} event={event} onClose={() => setEditing(false)} onSaved={() => { setEditing(false); refresh(); }}/>
    </>}
  </>;
}
